
export default function Home() {
  return (
    <>
      <section id="home" className="h-screen ml-80">
        <h1 className=".title">Home</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora laborum ipsa sint explicabo tenetur! Ullam, quas rerum. Ratione possimus nobis odit nam tenetur numquam deleniti, soluta, corrupti veritatis maiores iste eaque porro exercitationem. Est odit accusamus, temporibus quaerat veniam vel? Perferendis aliquam et quam sapiente placeat sequi doloribus quidem debitis quos ex natus eius non at illum soluta alias minus sunt deleniti, magnam pariatur ratione tempora eveniet ducimus impedit? Repellat, odio culpa. Nostrum porro optio aspernatur assumenda dicta mollitia provident non, recusandae magnam, voluptate animi aliquam. Sed cum perspiciatis ipsa repudiandae saepe recusandae sapiente nobis, illum odio. Ab eum quas tempore ex rerum dignissimos, quae alias doloribus mollitia optio iusto voluptates molestias? Sint aut ullam hic possimus autem magnam expedita, est rem natus voluptatum corrupti, molestias quod laboriosam temporibus sit animi molestiae quis obcaecati harum soluta omnis. Porro eius alias ratione unde, expedita magnam sapiente praesentium harum voluptas hic odio suscipit illo mollitia dolorem doloremque aut distinctio magni non provident reiciendis, nemo, vitae quisquam rem. Sit nobis obcaecati ea odit doloribus, ratione non repellat mollitia quaerat soluta natus eos, qui sed, quia excepturi! Tempora iusto, nemo quaerat dignissimos deserunt exercitationem natus non dicta veritatis molestias sapiente quam beatae fugit! Nemo quisquam maxime dolor! Eveniet ducimus impedit nam tempore vitae, perferendis suscipit cumque fugit tempora non iure ipsa saepe autem pariatur officiis quisquam quas aliquam accusamus at eum, delectus veritatis distinctio laboriosam nostrum. Voluptatibus assumenda ad amet exercitationem architecto enim eaque provident tenetur, blanditiis sit numquam voluptates est corrupti officia nesciunt eius quia hic impedit ullam quis voluptas beatae! Impedit sint eum eos, iusto numquam ea vero. Perspiciatis corrupti magnam nobis voluptatem debitis a voluptas. Ipsum corporis dolorum cumque officiis praesentium saepe vero ad a iure, labore, culpa esse nihil fuga natus accusamus reprehenderit porro exercitationem eius ea recusandae error asperiores. Pariatur similique aut dicta nisi fugiat officia voluptatibus odit incidunt voluptate at ratione odio quas, suscipit assumenda! Ab quas perferendis veritatis maxime. Eaque magnam voluptate rerum iure molestias deserunt incidunt, tenetur mollitia quos accusamus aliquid libero odit beatae laudantium quasi totam ipsa nesciunt ipsam aspernatur laboriosam excepturi quis cupiditate? Ipsam quam, tempore eum repudiandae sapiente aperiam soluta laboriosam asperiores maxime quae aspernatur consequatur delectus, nisi, distinctio cumque facere ad. Magni dolorum totam necessitatibus nihil est officiis et vitae nobis placeat iste, nisi nesciunt ea reprehenderit dolor hic, numquam tempore beatae reiciendis quisquam, doloremque voluptas? Quaerat eum possimus nihil accusamus nisi?</p>
      </section> 
    </>
  )
}
